const myProjects = [
  {
    id: 1,
    title: 'Guaranteed Future',
    shortDescription:
      'Designed to assist students. Developed using React Native, this intuitive and simple application facilitates efficient time management for users',
    link: 'https://play.google.com/store/apps/details?id=com.matheuschiodi.FuturoGarantido',
    image: require('../assets/projects/futurogarantido.png'),
    ti: 'React Native',
    rank: 1,
  },
  {
    id: 2,
    title: 'Dual Game',
    shortDescription:
      'Designed as a lightweight, user-friendly gaming platform, it provides enjoyable games for friends to play together.',
    link: 'https://play.google.com/store/apps/details?id=com.matheuschiodi.dualgame',
    image: require('../assets/projects/dualgame.png'),
    ti: 'React Native',
    rank: 1,
  },
  {
    id: 3,
    title: 'Pomodoro Prime Timer',
    shortDescription:
      'Project was created with the intention of helping people learn and improve their productivity.',
    link: 'https://play.google.com/store/apps/details?id=com.matheuschiodi.PomodoroPrimeTimer',
    image: require('../assets/projects/pomodoro_prime_timer.png'),
    ti: 'React Native',
    rank: 1,
  },
  {
    id: 4,
    title: 'MChiodi - Training Record',
    shortDescription: 'Is a tool designed to assist athletes.',
    link: 'https://play.google.com/store/apps/details?id=com.matheuschiodi.TrainingRecord',
    image: require('../assets/projects/trainingrecord.png'),
    ti: 'React Native',
    rank: 1,
  },
  {
    id: 5,
    title: 'Project Windows',
    shortDescription: 'This educational project was crafted using ReactJS.',
    link: 'https://matheuschiodi.github.io/windows/',
    image: require('../assets/projects/windows.png'),
    ti: 'ReactJS',
    rank: 2,
  },
  {
    id: 6,
    title: 'Project Shop',
    shortDescription:
      'Welcome to our Online Marketplace for Electronic Projects!',
    link: 'https://matheuschiodi.github.io/Project-Shop/',
    image: require('../assets/projects/projectShop.png'),
    ti: 'ReactJS',
    rank: 2,
  },
  {
    id: 7,
    title: 'Project Tic Tac Toe',
    shortDescription: 'The Tic Tac Toe (Noughts and Crosses) project.',
    link: 'https://matheuschiodi.github.io/tic-tac-toe/',
    image: require('../assets/projects/tic_tac_toe.png'),
    ti: 'ReactJS',
    rank: 2,
  },
  {
    id: 8,
    title: 'NLW Spacetime',
    shortDescription:
      'During this inspiring event, I had the opportunity to participate and dive into the creation of a memory-recalling application using powerful technologies such as ReactJS, React Native, NextJS, among others.',
    link: 'https://matheuschiodi.github.io/NLW-Spacetime-not-Prisma/',
    image: require('../assets/projects/spacetime.png'),
    ti: 'ReactJS',
    rank: 2,
  },
  {
    id: 9,
    title: 'TCC Parque Vivo',
    shortDescription: 'Developed for the TIIEM at IFSP - Campus Araraquara.',
    link: 'https://github.com/MatheusChiodi/TccParqueVivoV1',
    image: require('../assets/projects/parquevivo.png'),
    ti: 'HTML',
    rank: 3,
  },
  {
    id: 10,
    title: 'Training Record version web',
    shortDescription: 'Was meticulously developed using the ReactJS library.',
    link: 'https://matheuschiodi.github.io/Training/',
    image: require('../assets/projects/trainingrecordweb.png'),
    ti: 'ReactJS',
    rank: 2,
  },
  {
    id: 11,
    title: 'New Spotify beta',
    shortDescription: 'Was developed using ReactJS and TailwindCSS.',
    link: 'https://matheuschiodi.github.io/spotify/',
    image: require('../assets/projects/spotify.png'),
    ti: 'ReactJS',
    rank: 2,
  },
  {
    id: 12,
    title: 'Card Manager',
    shortDescription:
      'Is an innovative app designed for efficient personal finance management.',
    link: 'https://play.google.com/store/apps/details?id=com.matheuschiodi.Invest',
    image: require('../assets/projects/cardmanager.png'),
    ti: 'React Native',
    rank: 1,
  },
  {
    id: 13,
    title: 'Help link',
    shortDescription: '"Help Link" is an innovative resource.',
    link: 'https://matheuschiodi.github.io/HelpLinks/',
    image: require('../assets/projects/helplink.png'),
    ti: 'ReactJS',
    rank: 2,
  },
];

export default myProjects;
